name: Go Cross-Platform Build CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - { goos: linux, goarch: amd64, runner: ubuntu-latest, name_suffix: "linux-amd64" }
          - { goos: windows, goarch: amd64, runner: windows-latest, name_suffix: "windows-amd64", exe_suffix: ".exe" }
          - { goos: darwin, goarch: amd64, runner: macos-latest, name_suffix: "darwin-amd64" }
          - { goos: darwin, goarch: arm64, runner: macos-latest, name_suffix: "darwin-arm64" }
          - { goos: linux, goarch: arm64, runner: ubuntu-latest, name_suffix: "linux-arm64" }

    runs-on: ${{ matrix.target.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download Go modules
        run: go mod download

      - name: Build for ${{ matrix.target.goos }}/${{ matrix.target.goarch }}
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}
        shell: bash
        run: |
          output_name="app-${{ matrix.target.name_suffix }}${{ matrix.target.exe_suffix }}"
          echo "Building $output_name..."
          go build -v -ldflags="-s -w" -o "$output_name" main.go

      - name: Upload ${{ matrix.target.name_suffix }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.target.name_suffix }}
          path: app-${{ matrix.target.name_suffix }}${{ matrix.target.exe_suffix }}